### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JuliusMaerz**

### CODE REVIEW

**Comment by vandenman** [comment]
Hi @JuliusMaerz, it looks like you only pushed changes to the README in this pull request. Was this intentional? This will complicate the reviewers' job a little. If you're having issues with GitHub please let me know!

@AlexisDaniels & @ToscaBeijaert, it's probably more useful to give feedback on https://github.com/Programming-The-Next-Step-2021/JPEG_Compression_Study/blob/main/Compression_code.py and https://github.com/Programming-The-Next-Step-2021/JPEG_Compression_Study/blob/main/Code_experimental_design.py in addition to the changes here.

**Comment by JuliusMaerz** [comment]
Hi, yeah sorry the last pull request, that I also accidentally added on Canvas was pretty useless. I just added another pull request which contains my three main files, it probably makes more sense to review that.

**Comment by JuliusMaerz** [comment]
This one: https://github.com/Programming-The-Next-Step-2021/JPEG_Compression_Study/pull/10

**Comment by ToscaBeijaert** [comment]
Alright, no problemo!

Op za 15 mei 2021 om 09:42 schreef JuliusMaerz ***@***.***>:

**Pull request merged**
